### ISSUE TITLE
Close Workers when Manager is closed

### ISSUE THREAD

**Issue by meehaws** [gravity9-tech/mongo-cse#60]
When MongoCseManager is closed, workers are still working and keep throwing the exception:

```
java.lang.IllegalStateException: state should be: open
	at com.mongodb.assertions.Assertions.isTrue(Assertions.java:81) ~[mongodb-driver-core-4.10.1.jar:?]
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:170) ~[mongodb-driver-core-4.10.1.jar:?]
	at com.mongodb.internal.connection.AbstractMultiServerCluster.getDescription(AbstractMultiServerCluster.java:54) ~[mongodb-driver-core-4.10.1.jar:?]
	at com.mongodb.client.internal.ClientSessionBinding.isConnectionSourcePinningRequired(ClientSessionBinding.java:135) ~[mongodb-driver-sync-4.10.1.jar:?]
	at com.mongodb.client.internal.ClientSessionBinding.getReadConnectionSource(ClientSessionBinding.java:89) ~[mongodb-driver-sync-4.10.1.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:306) ~[mongodb-driver-core-4.10.1.jar:?]
	at com.mongodb.internal.operation.ChangeStreamOperation.execute(ChangeStreamOperation.java:185) ~[mongodb-driver-core-4.10.1.jar:?]
	at com.mongodb.internal.operation.ChangeStreamOperation.execute(ChangeStreamOperation.java:55) ~[mongodb-driver-core-4.10.1.jar:?]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:153) ~[mongodb-driver-sync-4.10.1.jar:?]
	at com.mongodb.client.internal.ChangeStreamIterableImpl.execute(ChangeStreamIterableImpl.java:212) ~[mongodb-driver-sync-4.10.1.jar:?]
	at com.mongodb.client.internal.ChangeStreamIterableImpl.cursor(ChangeStreamIterableImpl.java:187) ~[mongodb-driver-sync-4.10.1.jar:?]
	at com.gravity9.mongocse.MongoChangeStreamWorker.processData(MongoChangeStreamWorker.java:95) [mongo-change-stream-enhancer-1.0.0-beta.jar:?]
	at com.gravity9.mongocse.MongoChangeStreamWorker.run(MongoChangeStreamWorker.java:83) [mongo-change-stream-enhancer-1.0.0-beta.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
14:49:11.039 [Thread-0] ERROR com.gravity9.mongocse.MongoChangeStreamWorker csem_sample_mflix_commnets_0_partition_0 - Exception while processing change
```

**Comment by Dominik-Matysiak-gravity** [comment]
problem was resolved here https://github.com/gravity9-tech/mongo-cse/pull/80
